modules:
  - tasrif.processing_pipeline: [sequence]
  - tasrif.data_readers.fitbit_interday_dataset: [fitbit_interday_dataset]
  - tasrif.processing_pipeline.pandas: [convert_to_datetime, set_index]
  - tasrif.processing_pipeline.observers: [logging]

pipeline:
  $sequence:
    processing_operators:
      - $fitbit_interday_dataset:
          folder_path: ${FITBIT_INTERDAY_PATH}
          table_name: Food Log
      - $convert_to_datetime:
          feature_names: [Date]
          infer_datetime_format: true
      - $set_index:
          keys: Date
    observers:
      - $logging
