modules:
  - tasrif.processing_pipeline: [sequence, compose]
  - tasrif.data_readers.fitbit_intraday_dataset: [fitbit_intraday_dataset]
  - tasrif.processing_pipeline.pandas: [convert_to_datetime, set_index, json_normalize, as_type, merge]

pipeline:
  - $sequence:
    - $compose:
      - $fitbit_intraday_dataset:
          folder_path: ${FITBIT_INTRADAY_PATH}
          table_name: Very_Active_Minutes
          num_files: 5
      - $fitbit_intraday_dataset:
          folder_path: ${FITBIT_INTRADAY_PATH}
          table_name: Lightly_Active_Minutes
          num_files: 5
      - $fitbit_intraday_dataset:
          folder_path: ${FITBIT_INTRADAY_PATH}
          table_name: Moderately_Active_Minutes
          num_files: 5
      - $fitbit_intraday_dataset:
          folder_path: ${FITBIT_INTRADAY_PATH}
          table_name: Sedentary_Minutes
          num_files: 5
    - $json_normalize
    - $convert_to_datetime:
        feature_names: [dateTime]
        infer_datetime_format: true
    - $set_index:
        keys: dateTime
    - $as_type:
        dtype:
          value: int32
    - $merge:
        'on': dateTime
        how: outer