modules:
  - tasrif.processing_pipeline: [sequence]
  - tasrif.data_readers.fitbit_intraday_dataset: [fitbit_intraday_dataset]
  - tasrif.processing_pipeline.pandas: [convert_to_datetime, set_index, json_normalize, as_type]
  - tasrif.processing_pipeline.custom: [drop_index_duplicates, resample]

pipeline:
  - $sequence:
    - $fitbit_intraday_dataset:
        folder_path: !ENV FITBIT_INTRADAY_PATH /mnt/data/fitbit-data/fitbit-interday-sample.csv/
        table_name: Heart_Rate
        num_files: 5
    - $json_normalize
    - $convert_to_datetime:
        feature_names: [dateTime]
        infer_datetime_format: true
    - $set_index:
        keys: dateTime
    - $as_type:
        dtype:
          value.bpm: int32
          value.confidence: int32
    - $drop_index_duplicates:
        keep: first
    - $resample:
        rule: 30s
        aggregation_definition:
          value.bpm: mean
          value.confidence: mean