# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
        - id: isort
          args: ["--profile", "black"]
          name: isort (python)
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__ --rcfile=.pylintrc --score=n
        language: system
        files: ^tasrif/
        types: [file, python]
        exclude: test
-   repo: https://github.com/terrencepreilly/darglint.git
    rev: v1.8.0
    hooks:
    -   id: darglint
        args: ["--docstring-style", "google", "--ignore-regex", "^_(.*)"]
        files: ^tasrif/
        types: [file, python]
