modules:
  - tasrif.processing_pipeline: [sequence, compose, map_iterable, print]
  - tasrif.data_readers.fitbit_interday_dataset: [fitbit_interday_dataset]
  - tasrif.processing_pipeline.pandas: [convert_to_datetime, set_index, merge, as_type, drop_features]
  - tasrif.processing_pipeline.custom: [create_feature, aggregate, flatten, normalize]

pipeline:
  - $sequence:
    - $compose:
      - $sequence:
        - $fitbit_interday_dataset:
            folder_path: !ENV ${FITBIT_INTERDAY_PATH} /mnt/data/fitbit-data
            table_name: Activities
        - $convert_to_datetime:
            feature_names: Date
            infer_datetime_format: true
        - $as_type:
            dtype:
              Date: str
        - $drop_features:
            feature_names: [Floors, Activity Calories, Minutes Lightly Active, Minutes Fairly Active, Minutes Very Active]
        - $set_index:
            keys: Date
      - $sequence:
        - $fitbit_interday_dataset:
            folder_path: !ENV ${FITBIT_INTERDAY_PATH} /mnt/data/fitbit-data
            table_name: Sleep
        - $convert_to_datetime:
            feature_names: [Start Time, End Time]
            infer_datetime_format: true
        - $create_feature:
            feature_name: Date
            feature_creator: lambda df:df['End Time'].date()
        - $drop_features:
            feature_names: ['Minutes Awake', 'Number of Awakenings', 'Time in Bed', 'Minutes REM Sleep', 'Minutes Light Sleep', 'Minutes Deep Sleep']
        - $aggregate:
            groupby_feature_names: Date
            aggregation_definition:
                Minutes Asleep: sum
        - $as_type:
            dtype:
              Date: str
        - $set_index:
            keys: Date
    - $flatten
    - $merge:
        'on': Date
        how: inner
    - $create_feature:
        feature_name: Minutes Non Sedentary
        feature_creator: "lambda df: 1440 - df['Minutes Sedentary'] - df['Minutes Asleep_sum']"
