modules:
  - tasrif.processing_pipeline: [sequence]
  - tasrif.data_readers.siha_dataset: [siha_dataset]
  - tasrif.processing_pipeline.custom: [jq]
  - tasrif.processing_pipeline.pandas: [json_normalize, set_index, convert_to_datetime, as_type]

pipeline:
  $sequence:
    - $siha_dataset:
        folder_path: ${SIHA_PATH}
        table_name: Calories
    - $jq:
        expression: 'map({patientID} + .data.activities_tracker_calories[].data."activities-tracker-calories"[0])'
    - $json_normalize
    - $convert_to_datetime:
        feature_names: [dateTime]
        infer_datetime_format: true
    - $set_index:
        keys: dateTime
    - $as_type:
        dtype:
          value: float32