modules:
  - tasrif.processing_pipeline: [sequence]
  - tasrif.data_readers.withings_dataset: [withings_dataset]
  - tasrif.processing_pipeline.custom: [create_feature, aggregate]
  - tasrif.processing_pipeline.pandas: [convert_to_datetime, set_index]

pipeline:
  $sequence:
    - $withings_dataset:
        file_name: ${WITHINGS_PATH}sleep.csv
        table_name: Sleep
    - $convert_to_datetime:
        feature_names: [from, to]
        infer_datetime_format: true
    - $create_feature:
        feature_name: Date
        feature_creator: lambda df:df['to'].date()
    - $aggregate:
        groupby_feature_names: Date
        aggregation_definition:
          Heart rate (min): mean
          Heart rate (max): mean
          Average heart rate: mean
          Duration to sleep (s): sum
          Duration to wake up (s): sum
          Snoring (s): sum
          Snoring episodes: sum
          rem (s): sum
          light (s): sum
          deep (s): sum
          awake (s): sum
    - $set_index:
        keys: Date